import { ProgramItem, InstallationItem, OpenCallCategory, GlobalNetworkItem } from "./types";

export const programsData: ProgramItem[] = [
  {
    id: "festival",
    title: "Festival",
    subtitle: "AI Cinema",
    icon: "movie",
    description: "The global benchmark for computer-generated filmmaking and generative moving images.",
    longDescription: "The Festival of AI Cinema is an annual exhibition showcasing works created entirely, or in part, through artificial intelligence and automated systems. Bringing together pioneers of algorithmic cinema and leading design agencies, the program aims to redefine the cinematic experience by challenging conventional structures of authorship, continuity, and production.",
    schedule: "September 12 – October 18, 2026",
    curator: "Dr. Elena Vance"
  },
  {
    id: "dreama",
    title: "Dreama",
    subtitle: "Dream Experiences",
    icon: "bedtime",
    description: "Multi-sensory environments translating subconscious signals into real-time digital architecture.",
    longDescription: "Dreama leverages EEG biometric signals, neural translation, and generative spatial render engines to turn dreaming states into visual, audible, and physically felt rooms. Each visit is unique, dynamically generated by the collective focus and neurological feedback of the participants.",
    schedule: "Ongoing Installation",
    curator: "Sora Takahashi"
  },
  {
    id: "conversations",
    title: "Conversations",
    subtitle: "Future Storytelling",
    icon: "forum",
    description: "Symposiums and talks led by digital theorists, neural artists, and creative technologists.",
    longDescription: "A curated series of roundtables, panels, and academic critiques examining the ethical, practical, and philosophical frameworks of creative cognitive collaboration. How do we navigate copyrights when training models? What constitutes raw original creativity in a post-human landscape?",
    schedule: "Bi-Weekly Panels",
    curator: "Marcus Sterling"
  },
  {
    id: "community",
    title: "Community",
    subtitle: "Artists, filmmakers...",
    icon: "groups",
    description: "A continuous laboratory providing computational resources and hardware Access to builders worldwide.",
    longDescription: "Our resident community is a thriving network of painters, developers, novelists, and sound engineers. Through joint fellowships with high-performance computing clusters, we award open-source server credits, hardware modules, and physical incubator workstations designed to facilitate experimental art.",
    schedule: "Year-Round Fellowship",
    curator: "Inès Moreau"
  }
];

export const installationsData: InstallationItem[] = [
  {
    id: "theater",
    num: "01",
    title: "Dream Theater",
    tagline: "Unconscious Screenplay Projection Room",
    description: "A cinematic space projecting continuous, non-repeating narratives trained on historical dream journals and surrealist literature, evolving in real-time.",
    narrative: "An infinite film composed of thousands of algorithmic fragments. As a viewer, your biological rhythms and ambient focus are measured discreetly via infrared scanners, gently nudging the camera angle, narrative pace, and color hue to suit the collective presence. No two screenings are identical in duration, plot, or visual output.",
    duration: "Infinite loop (Avg. viewing 25 mins)",
    spaceRequired: "Darkened hemispherical projection gallery",
    technicalSpecs: [
      "24,000 Lumens Laser Projection",
      "Algorithmic dynamic video synthesizer",
      "Biometric tracking telemetry suite"
    ]
  },
  {
    id: "room",
    num: "02",
    title: "Dream Room",
    tagline: "Responsive Haptic Environment",
    description: "A physical chamber constructed with smart materials that physically warp and pulse in direct response to bio-electrical audio signals.",
    narrative: "Step inside a completely soundproofed cube lined with fluidic membrane panels. High-resolution ultrasonic transducers target your skin with safe pressure frequencies, giving tangible shape to invisible wave systems. The room resonates in deep registers, letting you feel the physical volume of a virtual field of motion.",
    duration: "10-minute individual sessions",
    spaceRequired: "10x10x10ft soundproofed room with floating floor",
    technicalSpecs: [
      "128-channel spatial haptic array",
      "Ultrasonic transducer modules",
      "Sub-bass resonant plates"
    ]
  },
  {
    id: "archive",
    num: "03",
    title: "Dream Archive",
    tagline: "Interactive Lexicon of Subconscious Data",
    description: "A digital inventory aggregating and cataloging thousands of generated dream sequences into a navigable subterranean network.",
    narrative: "This digital archive allows visitors to wander through a three-dimensional mapping of dream classifications. Grouped by core archetype themes (falling, flight, language-loss, high-altitude cities), users can retrieve metadata, generate conceptual representations of their own sleep themes, and watch historical algorithmic visualizations of sleep records.",
    duration: "Self-paced navigation",
    spaceRequired: "Multi-station touch console terminal area",
    technicalSpecs: [
      "Interactive multi-touch tables",
      "Archival search vector engine",
      "OLED high-contrast reference displays"
    ]
  },
  {
    id: "sleeplab",
    num: "04",
    title: "Future Sleep Lab",
    tagline: "Generative Neurological Feedback Pod",
    description: "A specialized isolation pod exploring safe, slow-wave sleep synthesis through atmospheric stimulation.",
    narrative: "A clinical-art hybrid. The Future Sleep Lab utilizes low-intensity sensory guidance (rhythmic pink noise, gentle humidity variance, and monochromatic spectrum illumination) to align brainwave patterns into optimal sleep cycles, capturing the transition state to generate abstract dreamscapes.",
    duration: "45-minute timed sessions",
    spaceRequired: "Sealed acoustic isolation capsule",
    technicalSpecs: [
      "Slow-wave acoustic synchronizer",
      "Micro-climate humidity controller",
      "EEG active analysis headset"
    ]
  }
];

export const openCallCategories: OpenCallCategory[] = [
  {
    id: "films",
    title: "AI Films",
    description: "Cinematic works utilizing generative engines for screenplays, visual development, editing, or rendering.",
    deliverables: "High-resolution video render (up to 20 mins) + prompt structure overview."
  },
  {
    id: "hybrid",
    title: "Hybrid Narratives",
    description: "Interactive systems that blend physical physical props with digital overlays, or responsive gaming mediums.",
    deliverables: "Interactive prototype deck OR live deployment URL + video documentation."
  },
  {
    id: "immersive",
    title: "Immersive Experiences",
    description: "Digital compositions designed specifically for spatial rendering, dome projections, or dome architecture.",
    deliverables: "Render blueprints + complete tech rider + surround audio specifications."
  },
  {
    id: "experimental",
    title: "Experimental Storytelling",
    description: "Boundary-breaking projects utilizing custom custom codebases, generative APIs, or synthetic actor rigs.",
    deliverables: "Source files/repositories + whitepaper methodology statement."
  }
];

export interface AdvisoryMember {
  role: string;
  category: string;
  description: string;
  status?: string;
}

export const advisoryCircle: AdvisoryMember[] = [
  {
    role: "Film & Cinematic Arts",
    category: "Jury Co-Chair",
    description: "Curating the evolution of motion picture and screen grammar through computational lenses."
  },
  {
    role: "AI & Computational Theory",
    category: "Technical Jury",
    description: "Defining ethical, procedural, and generative frameworks for machine imagination."
  },
  {
    role: "Immersive & Spatial Media",
    category: "Spatial Jury",
    description: "Bridging the gap between institutional heritage, physical spaces, and digital futures."
  }
];

export interface FestivalExperience {
  id: string;
  title: string;
  description: string;
  icon: string;
  tag?: string;
}

export type FestivalPillar = FestivalExperience;

export const festivalExperiences: FestivalExperience[] = [
  {
    id: "awards",
    title: "Cinema Awards",
    description: "Recognizing excellence in AI-powered filmmaking, procedural world-building, and automated storytelling across 10 official award classes.",
    icon: "award",
    tag: "AWARDS & COMPETITION"
  },
  {
    id: "panel",
    title: "Future Cinema Panel",
    description: "Industry conversations and critical discourse on the future of human creativity, authorship, and visual culture with global studio leaders and tech founders.",
    icon: "forum",
    tag: "CONVERSATIONS"
  },
  {
    id: "immersive_future_reality",
    title: "Immersive Future Reality",
    description: "Spatial, holographic, and interactive installations combined with real-time, audience-driven generative cinema co-created with Dreama.",
    icon: "vrpandemonium",
    tag: "SPATIAL & INTERACTIVE REALITY"
  },
  {
    id: "film_screening",
    title: "Film Screening",
    description: "Curated theatrical screenings of groundbreaking AI-native short films, generative cinema selections, and international competition nominees on the big screen at Regal Union Square.",
    icon: "theaters",
    tag: "THEATRICAL SCREENINGS"
  }
];

export const festivalPillars = festivalExperiences;

export interface CompetitionCategoryItem {
  id: string;
  title: string;
  description: string;
  requirements: string;
}

export const competitionCategories: CompetitionCategoryItem[] = [
  {
    id: "best_film",
    title: "Best Film",
    description: "Overall achievement",
    requirements: "Full narrative or cinematic export, complete production credits, and creative statement."
  },
  {
    id: "best_narrative",
    title: "Best Narrative",
    description: "Story + structure",
    requirements: "Narrative structure documentation, screenplay/treatment, and complete film export."
  },
  {
    id: "best_character",
    title: "Best Character",
    description: "Character + performance",
    requirements: "Character performance documentation, actor/synthetic calibration breakdown, and video submission."
  },
  {
    id: "best_visual",
    title: "Best Visual",
    description: "Cinematic image-making",
    requirements: "Cinematography stills, visual rendering breakdown, and master high-fidelity project export."
  },
  {
    id: "best_creative_use_of_ai",
    title: "Best Creative Use of AI",
    description: "AI-native creativity",
    requirements: "AI-native toolchain documentation, workflow methodology, and final cinematic export."
  },
  {
    id: "best_music_sound",
    title: "Best Music / Sound",
    description: "Sonic storytelling",
    requirements: "Multichannel audio master / spatial stems, sound design breakdown, and film export."
  },
  {
    id: "best_costume_design",
    title: "Best Costume Design",
    description: "Costume + character aesthetics",
    requirements: "Costume design portfolio, digital textile render sheets, and aesthetic lookbook."
  },
  {
    id: "best_worldbuilding",
    title: "Best Worldbuilding",
    description: "World design + imagination",
    requirements: "World architectural design layout, procedural environment documentation, and scene render."
  },
  {
    id: "best_immersive_experience",
    title: "Best Immersive Experience",
    description: "Immersive + experiential storytelling",
    requirements: "Spatial computing build, interactive project export, or experiential installation demo."
  },
  {
    id: "special_jury_award",
    title: "Special Jury Award",
    description: "Exceptional vision + boundary-pushing work",
    requirements: "Comprehensive project bundle, visionary artist statement, and uncompressed master render."
  }
];

export interface KeyStatItem {
  value: string;
  label: string;
  sub: string;
}

export const keyStatsData: KeyStatItem[] = [
  { value: "5,000+", label: "Audience Members", sub: "Annual spatial attendance in NYC" },
  { value: "4,000+", label: "Global Submissions", sub: "Averaged across 12 digital channels" },
  { value: "50+", label: "Countries Represented", sub: "Global cinematic representation" },
  { value: "80+", label: "Official Selections", sub: "Premiering on our high-contrast arrays" },
  { value: "30+", label: "Industry Partners", sub: "Leading agencies and tool providers" },
  { value: "200+", label: "Industry Meetings", sub: "Matchmaking panels facilitated" },
  { value: "50M+", label: "Social Reach", sub: "Global digital narrative impact" }
];

export const globalNetworkData: GlobalNetworkItem[] = [
  {
    id: "soho_16th_edition_premiere",
    title: "SOHO 16th Edition: Cinema Premiere & Keynote",
    subtitle: "Monumental Screening & Executive Panel in New York City",
    location: "Regal Union Square, New York",
    city: "New York, NY",
    year: "16th Edition • Oct 7–13, 2025",
    host: "soho",
    category: "Mainstage Screening",
    badge: "New York City • 16th Edition",
    description: "Opening night mainstage keynote and premiere showcase under the monumental SOHO architectural projection (#SOHO16 #SIFFNYC) featuring festival executive directors and world premiere filmmakers.",
    highlights: [
      "Mainstage keynote in landmark Manhattan cinema auditorium",
      "Official 16th Edition festival kickoff & screening sequences",
      "Filmmaker Q&A discussions exploring next-gen storytelling",
      "Over 80+ international film selections screened across 7 days"
    ],
    attendees: "Executive Leadership & World Premiere Directors",
    imageUrl: "/soho16.jpeg",
    visualType: "theater_keynote",
    accentColor: "#8B5CF6"
  },
  {
    id: "soho_gala_step_repeat",
    title: "Broome Street Series: Shorts Program G",
    subtitle: "Official SOHO International Film Festival Curated Shorts Showcase",
    location: "New York City • Regal Union Square",
    city: "New York, NY",
    year: "Official Selection",
    host: "soho",
    category: "Shorts Program G",
    badge: "SOHO • Broome Street Series",
    description: "Official curated poster showcase for the Broome Street Series Shorts Program G at the SOHO International Film Festival, featuring acclaimed independent selections including TAPER, DIZZY, Catalogue of Noses, RED TEAM, millie, and LIFESAVER.",
    highlights: [
      "Official Selection of the SOHO International Film Festival",
      "Featured shorts: TAPER, DIZZY, Catalogue of Noses, RED TEAM, millie, LIFESAVER",
      "Curated cinematic screenings celebrating diverse independent voices",
      "Theatrical presentation at Regal Union Square, NYC"
    ],
    attendees: "Official Selection Filmmakers & Delegations",
    imageUrl: "/5.png",
    visualType: "step_and_repeat",
    accentColor: "#E63946"
  },
  {
    id: "harvard_xr_keynote",
    title: "HXR Summit: The Evolution from PC to Spatial Computing",
    subtitle: "Packed Auditorium Keynote: PC → Web → Mobile → VR → XR+",
    location: "Harvard University • Cambridge, MA",
    city: "Cambridge, MA",
    year: "Academic Keynote",
    host: "hxr",
    category: "Academic & Tech Keynote",
    badge: "Harvard University • Tech Keynote",
    description: "A packed amphitheater address mapping out the generational paradigm shifts of computing from early PC hardware and the World Wide Web to mobile ecosystems, VR headsets, and spatial XR+ environments.",
    highlights: [
      "Keynote address to packed auditorium of 400+ researchers and students",
      "Framework tracking computational evolution: PC → Web → Mobile → VR → XR",
      "Focus on spatial computing, generative visual systems, and AI narrative",
      "Bridging Ivy League academia, venture capital, and digital artists"
    ],
    attendees: "400+ Harvard Fellows, Engineers & Creators",
    imageUrl: "/images (1).jpeg",
    visualType: "auditorium_lecture",
    accentColor: "#06B6D4"
  },
  {
    id: "harvard_xr_inaugural",
    title: "HXR 2026 Conference",
    subtitle: "The Premier Forum for Immersive, Spatial and AI Pioneers",
    location: "Graduate School of Design at Harvard University + Online Global Stream",
    city: "Cambridge, MA",
    year: "2026 Conference",
    host: "hxr",
    category: "Global Conference",
    badge: "Harvard GSD • Global Conference",
    description: "The 2026 Harvard XR Conference convening leading spatial developers, immersive designers, and creative theorists at the Graduate School of Design at Harvard University alongside a worldwide livestream.",
    highlights: [
      "Convening leading spatial computing and immersive technology innovators",
      "Hybrid global broadcast connecting creators and researchers across continents",
      "Exploration of spatial design, volumetric media, 3D interaction, and generative AI",
      "Pioneering nexus for ongoing NYC × Boston festival and academic partnerships"
    ],
    attendees: "Harvard Fellows, Designers, Engineers & Global Keynotes",
    imageUrl: "/2.jpeg",
    visualType: "harvard_inaugural",
    accentColor: "#3B82F6"
  },
  {
    id: "creator_network_nyc_cambridge",
    title: "NYC & Cambridge Creator Network",
    subtitle: "Independent Filmmakers, Researchers, and Creative Technologists",
    location: "New York City & Cambridge, MA",
    city: "New York & Cambridge",
    year: "Active Cohort",
    host: "soho",
    category: "Creator Alliances",
    badge: "CREATOR NETWORK",
    description: "Connecting independent film directors, spatial designers, and AI creators across New York screening rooms, industry salons, and Boston research labs.",
    highlights: [
      "Cross-city filmmaker exchanges and co-creation workshops",
      "Open lab residencies for spatial and generative storytelling",
      "Bi-monthly creator salons in Manhattan and Harvard Square",
      "Collaborative incubator for selected festival projects"
    ],
    attendees: "Independent Filmmakers & Spatial Creators",
    imageUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80",
    visualType: "creator_cohort",
    accentColor: "#E63946"
  },
  {
    id: "hxr_2026_conference",
    title: "HXR Showcase 2026: XR+ From Pixel to Voxel",
    subtitle: "Annual Showcase Gathering of Spatial Computing Pioneers",
    location: "Harvard XR Hub • Cambridge / Boston, MA",
    city: "Cambridge, MA",
    year: "April 11, 2026",
    host: "hxr",
    category: "XR Showcase Cohort",
    badge: "Global XR Hub • 2026 Showcase",
    description: "The official HXR 2026 gathering uniting student founders, researchers, and spatial computing creators under the banner of 'XR+: From Pixel to Voxel', celebrating multidisciplinary breakthroughs.",
    highlights: [
      "Annual flagship convening of the Harvard XR community",
      "Pioneering research demos in voxel neural graphics and haptics",
      "Over 30+ cutting-edge XR projects and interactive demonstrations",
      "Cross-institutional fellowship with MIT, NYU, and global XR labs"
    ],
    attendees: "HXR Organizing Committee & Student Innovators",
    imageUrl: "https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?auto=format&fit=crop&w=1200&q=80",
    visualType: "hxr_team_2026",
    accentColor: "#EC4899"
  }
];


